# 配置文件
server:
  address: 1.1.1.1
  port: 9090
mysql:
  user: root
  password: 123456
  port: 3306
  database: go_shop
  host: 127.0.0.1
  csvSep: /
jwt:
  issuer: "2201"
  expireTime: 300
  secret: "2201"
log:
  level: info
  path: sss
  layout: "2006-01-02 15:04:05"
App:
  Port: 9090
