# 测试环境配置
MySQL:
  Host: xxxxx                 # 用其他同学的地址
  Port: 3306
  User: root
  Password: 123456
  Database: go_shop
  Charset: utf8mb4
  Config: sslmode=disable TimeZone=Asia/Shanghai

App:
  Port: 8090  