# 开发环境配置

MySQL:
  Host: 127.0.0.1
  Port: 3306
  User: root
  Password: 123456
  Database: go_shop
  Charset: utf8mb4
  Config: sslmode=disable TimeZone=Asia/Shanghai

App:
  Port: 8090

  
# server:
#  port: 3070
#  address: 192.168.0.220
# mysql:
#   # host: 10.0.106.24
#   user: root
#   password: 123456
#   port: 1949
#   # Database: server_learning
#   # Charset: utf8mb4
#   # Config: sslmode=disable TimeZone=Asia/Shanghai

# database: 2025