# 开发环境配置
server:
 port: 8083
 address: 127.0.0.1

#  编写开发和测试环境的MySQL数据库环境变量
MySQL:
  Host: 127.0.0.1
  Port: 3306
  Username: root
  Password: 123456
  Database: go_shop
  Charset: utf8mb4
  Config: sslmode=disable TimeZone=Asia/Shanghai

Database: 2025

# 指定运行端口
App:
  Port: 8090

# JWT配置
Jwt:
  Issuer: 牧牛火链
  ExpireTime: 70
  Secret: 牧牛火链