# 配置文件
server:
  address: 1.1.1.1 # 服务器地址
  port: 9090 # 服务器端口
mysql:
  user: root # 数据库用户名
  password: 123456 # 数据库密码
  host: 127.0.0.1 # 数据库地址
  port: 3306 # 数据库端口
  database: file_system # 数据库名称
  max-idle-conns: 10 # 连接池最大空闲连接数
  max-open-conns: 100 # 连接池最大连接数
  max-lifetime: 300s # 连接最大复用时间，不能超过mysql的wait_timeout
  csvSep: / # csv文件分隔符
jwt:
  issuer: "filesystem" # 签发者
  expireTime: 86400 # 过期时间，单位为秒(24h)
  secret: "filesystem_secret" # 密钥
log:
  level: info # 日志级别，可选值为 debug, info, warn, error, fatal, panic
  path: sss # 日志文件路径
  layout: "2006-01-02 15:04:05" # 日志时间格式
App:
  Port: 9090 # 应用端口
